name: budgetleaf
description: "A Financial Tracking App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  http: ^1.4.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  firebase_storage: ^12.4.6
  freezed_annotation: ^3.0.0
  fl_chart: ^0.71.0
  google_fonts: ^6.2.1

  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6
  basic_utils: ^5.7.0
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  external_path: ^2.0.1
  flutter_spinkit: ^5.1.0
  get_it: ^8.0.2
  json_annotation: ^4.8.0
  keyboard_dismisser: ^3.0.0
  package_info_plus: ^8.1.1
  provider: ^6.0.5
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.0-0.0.dev
  hive_generator:
    git:
      url: https://github.com/yura2000/hive.git
      ref: master
      path: hive_generator/
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
